apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: kcr-system
spec:
  template:
    spec:
      containers:
        - name: manager
          volumeMounts:
            - name: registry-config
              mountPath: /etc/containers/registries.conf
              subPath: registries.conf
      volumes:
        - name: registry-config
          configMap:
            name: registry-config