# This rule is not used by the project kcr itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the checkpoint-restore.kcr.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kcr
    app.kubernetes.io/managed-by: kustomize
  name: checkpoint-restore-checkpointschedule-editor-role
rules:
- apiGroups:
  - checkpoint-restore.kcr.io
  resources:
  - checkpointschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - checkpoint-restore.kcr.io
  resources:
  - checkpointschedules/status
  verbs:
  - get
