apiVersion: checkpoint-restore.kcr.io/v1
kind: CheckpointSchedule
metadata:
  name: kcr-example
  namespace: default
spec:
  schedule: '*/1 * * * *'
  selector:
    matchLabels:
      app: kcr-example
status:
  lastRunTime: "2025-07-30T09:54:00Z"
