name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install btrfs package
        run: sudo apt-get update && sudo apt-get install -y libgpgme-dev btrfs-progs 

      - name: Running Tests
        run: |
          go mod tidy
          make test
